//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Armour()
        {
            this.Ninjas = new HashSet<Ninja>();
        }
    
        public int ID { get; set; }
        public string Category { get; set; }
        public Nullable<int> Strength { get; set; }
        public Nullable<int> Intelligence { get; set; }
        public Nullable<int> Agility { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string Picture_location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ninja> Ninjas { get; set; }
    }
}
